# Generated by Django 4.2.4 on 2023-10-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactusdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('C_Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('C_City', models.CharField(blank=True, max_length=20, null=True)),
                ('C_Address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
