# Generated by Django 4.2.4 on 2023-10-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('R_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('R_Mobile', models.IntegerField(blank=True, null=True)),
                ('R_Email', models.EmailField(blank=True, max_length=20, null=True)),
                ('R_Address', models.CharField(blank=True, max_length=100, null=True)),
                ('R_Username', models.CharField(blank=True, max_length=20, null=True)),
                ('R_Password', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactusdb',
            name='C_Email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
    ]
